# Generated by Django 4.1.2 on 2023-04-05 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="pub_date",
            field=models.DateTimeField(auto_now=True, verbose_name="Date created"),
        ),
        migrations.CreateModel(
            name="FingerprintIdentity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("received_value", models.IntegerField(default=0, editable=False)),
                ("Reg_Date", models.DateTimeField(verbose_name="Date registered")),
                (
                    "entry_time",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Time of entry"
                    ),
                ),
                (
                    "exit_time",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Time of Exit"
                    ),
                ),
                (
                    "Jena_Employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="polls.employee"
                    ),
                ),
            ],
            options={
                "db_table": "FingerprintIdentity",
            },
        ),
        migrations.CreateModel(
            name="DailyAttendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_created",
                    models.DateTimeField(auto_now_add=True, verbose_name="Entry Date "),
                ),
                (
                    "daily_attendee",
                    models.ManyToManyField(to="polls.fingerprintidentity"),
                ),
            ],
        ),
    ]
