# Generated by Django 4.1.2 on 2023-04-10 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0002_employee_pub_date_fingerprintidentity_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dailyattendance",
            name="daily_attendee",
            field=models.ManyToManyField(blank=True, to="polls.fingerprintidentity"),
        ),
        migrations.AlterField(
            model_name="employee",
            name="Department",
            field=models.CharField(
                choices=[
                    ("Mining", "Mining"),
                    ("Engineering", "Engineering"),
                    ("Adminstration", "Admin"),
                ],
                default="Mining",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="fingerprintidentity",
            name="Reg_Date",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Date registered"
            ),
        ),
    ]
